name: Build and Push Temporal Worker

on:
  push:
    branches: [main]
    paths:
      - 'orchestrator/**'
      - '.github/workflows/ci-orchestrator.yaml'

env:
  IMAGE_NAME: temporal-orchestrator

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set ACR login server
        run: |
          echo "ACR_LOGIN_SERVER=$(az acr show --name acrtemporal${{ secrets.AZURE_RANDOM_SUFFIX }} --query loginServer -o tsv)" >> $GITHUB_ENV

      - name: Docker build
        run: |
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest -f orchestrator/Dockerfile .

      - name: Docker push
        run: |
          az acr login --name acrtemporal${{ secrets.AZURE_RANDOM_SUFFIX }}
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
