name: Build and Push Temporal Worker

on:
  push:
    branches: [main]
    paths:
      - 'orchestrator/**'
      - '.github/workflows/ci-orchestrator.yaml'

permissions:
  id-token: write  # ✅ required for OIDC login
  contents: read   # ✅ optional, but needed for actions/checkout

env:
  IMAGE_NAME: multiagent-orchestrator
  ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set ACR login server
        run: echo "ACR_LOGIN_SERVER=${{ env.ACR_NAME }}.azurecr.io" >> $GITHUB_ENV
        
      - name: Docker build and push
        run: |
            docker build -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest -f orchestrator/Dockerfile .
            az acr login --name $ACR_NAME
            docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest